{% set name = "pylatexenc" %}
{% set version = "2.6" %}
{% set sha256 = "18db52803a962eb1a8a7c7aa8d2e504f7eb70797434d5ae04a819e3b91605047" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/phfaist/pylatexenc/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - latexwalker = pylatexenc.latexwalker.__main__:main
    - latex2text = pylatexenc.latex2text.__main__:main
    - latexencode = pylatexenc.latexencode.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pylatexenc
  commands:
    - latexwalker --help
    - latex2text --help
    - latexencode --help

about:
  home: https://github.com/phfaist/pylatexenc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple LaTeX parser providing latex-to-unicode and unicode-to-latex conversion
  doc_url: https://pylatexenc.readthedocs.io/en/latest
  dev_url: https://github.com/phfaist/pylatexenc

extra:
  recipe-maintainers:
    - milljm
